Mellanox/mlnx-tools

debian/control
lsb_release is used to find the right folder in which to put the python
pre-compiled files.
=> Add lsb-release dependency

debian/rules
Also suppress python2 (mlnx_tune) generated dependency "python:any"
(older systems).
Also remove it when in end of line of sibstvars.
Signed-off-by: Tzafrir Cohen <nvidia@cohens.org.il>
=> debian: also suppress python:any dependency

tsbin/mlnx_bf_configure
Signed-off-by: Bodong Wang <bodong@nvidia.com>
=> mlnx_bf_configure: set lag hash mode to be off as default

python/dcbnetlink.py
Issue: 2804305
Signed-off-by: Roy Novich <royno@nvidia.com>
=> dcbnetlink: Use frombytes instead of depracated fromstring

sbin/mlnx_tune
In order to use set_xps_mask in the get_rings function, there must
be an existing tx queue with the same number as the rx_ring object we
use the set_xps_mask on.
This commit fix the get_rings function.
The commit add a restriction to handle the out of range problem.
=> Fix mlnx_tune out of range tx number

tsbin/mlnx_bf_configure
When first booted, the eswitch mode can be "none" instead
of legacy or switchdev.
Thus checking if the mode needs to be switched to legacy mode with
${eswitch_mode} == "switchdev"
does not work.
Instead check with:
${eswitch_mode} != "legacy"
Signed-off-by: Andy Roulin <andy.roulin@gmail.com>
=> tsbin/mlnx_bf_configure: fix switching to legacy mode

sbin/mlnx_tune
mlnx_tune is only supported by machines with python2 installed on.
This commit add python3 compatibility.
The commit also change the python interpreter
that mlnx_tune use to be the first interpreter that defined
on the environment's $PATH.
Signed-off-by: Shmuel Shaul <sshaul@nvidia.com>
=> Python 3 compatibility

sbin/mlnxofedctl
Add a new tool: mlnxofctl: a new command-line interface. Currently a wrapper around openibd / mlnx-en.d but later: a potential replacement.
Signed-off-by: Tzafrir Cohen <nvidia@cohens.org.il>
=> Add mlnxofedctl

python/mlnx_qos
Curerntly, with each buffer_size or prio2buffer command the script triggers the logic of both operations regardless of which one was called via the user.
Seperate the two flows, and trigger only the necessary functionality when requested from user.
Signed-off-by: Maher Sanalla <msanalla@nvidia.com>
=> mlnx_qos: Seperate buffer_size from prio2buffer commands

tsbin/mlnx_bf_configure
Set steering mode returns an error if the operation is not supported but this does not mean that the script cannot continue to work with the default steering mode.
=> tsbin/mlnx_bf_configure: Ignore set_steering_mode status

tsbin/mlnx_bf_configure
rdma system set netns exclusive - might fail with the following error: error: Device or resource busy
Retry rdma command till the timeout expires
Issue: 3563579
=> tsbin/mlnx_bf_configure: Added timeout on rdma system set netns command

tsbin/mlnx_bf_configure
In some cases mlxconfig fails with "Failed to open device" error. Try to rerun mlxconfig command with MLXCONFIG_TIMEOUT which is 60 seconds by default.
=> tsbin/mlnx_bf_configure: Add retry for mlxconfig

tsbin/mlnx_bf_configure
New upstream solution doesn't need to set ipsec mode anymore.
=> mlnx_bf_configure: Remove old out dated IPSec configuration

tsbin/mlnx_bf_configure
strongSwan automatically installs packet offloaded bypass IPsec policies (xfrm policies), but having IPsec policies prevents changing the eswitch mode. Therefore, we need to stop strongSwan before changing the eswitch mode, which will delete the policies, and then starting it again after changing the eswitch mode.
=> tsbin/mlnx_bf_configure: Stop strongswan before changing eswitch mode

python/mlnx_tune
Add ConnectX7 and BlueField3 to the SUPPORTED_CONSUMERS list.
=> Add ConnectX7 and BlueField3 to supported devices

python/mlnx_tune
There are OS's where /sys/devices/system/node/ includes different files with 'node' in the path.
this commit changed the parsing method to handle these kind of cases.
=> mlnx_tune: fix numa nodes parsing

tsbin/mlnx-sf
When creating > 500 sf using mlnx-sf one-by-one, every initialization of mlnx-sf issues "mlxdevm port show", which takes longer and longer time when existing number of SFs increases. In our experiments on BF2, with existing ~400 SFs, creating 1 SF takes around 10sec:
$ mlnx-sf -d 0000:03:00.0 -a create -n 440
Created SF: index=pci/0000:03:00.0/229718 hw_addr=00:00:00:00:00:00 \
sfnum=440 netif=eth0
real	0m10.214s
user	0m0.193s
sys	0m0.301s
And profiling shows majority of time spent in python init. With the patch, the time reduces to around 5 seconds.
--- attach two frame graph ---
see
perf-100: 100 existing SFs, 31% on _start(), 27% on mlxdevm
perf-400: 400 existing SF, 69% on _start(), 23% on mlxdevm
=> mlnx-sf: Move port show out of init

python/mlnx_qos, python/mlnx_tune
Python 3.12 upgraded the DeprecationWarning to a SyntaxWarning. Unlike DeprecationWarnings, SyntaxWarnings are displayed by default. this is why we see these erros only now.
currently, its not damaging the functionality, but In a future version of python, using invalid escape sequence in string literals is planned to eventually become a hard SyntaxError, that will break the script.
Fixed it by changing regex strings to raw strings.
=> mlnx_tune: Fix SyntaxWarning: invalid escape sequence with Python3.12

sbin/cma_roce_mode, sbin/cma_roce_tos
In the case if rdma_cm/<DEV> device directory exist before the script execution, prevent removing the directory on the exit.
That happens when end-user use OS vendor instructions how to set RoCE mode or configure tos and expect device directory to be present all the time.
Running cma_roce script removes that folder leads to unexpected system configuration change.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_infiniband_and_rdma_networks/configuring-roce_configuring-infiniband-and-rdma-networks
Another example is running multiple instances of the scripts at the same time. It leads to race conditions when one script creates the folder, but the other destroys it before first instance is trying to write to the folder.
=> Don't remove existing directory

tsbin/mlnx_bf_configure
In some cases like HBN, OVS will try to start while mlnx_bf_configure is still running and changing eswitch mode, this will can cause a race and to OVS to crash.
This change add an indication that mlnx_bf_configure finished so OVS service will wait on.
Issue: 3963483
=> tsbin/mlnx_bf_configure: Add indication that the script was done

udev/rules.d/82-net-setup-link.rules, udev/scripts/vf-net-link-name.sh
The 82-net-setup-link.rules UDEV rule calls vf-net-link-name.sh and then sets NAME="$env{NAME}". But in some cases, vf-net-link-name.sh does not return "NAME" and the result is error messages such as:
"systemd-udevd[164885]: Error changing net interface name 'eth101' to '': Invalid argument"
Additionally, this can break other UDEV rules that run after 82-net-setup-link.rules. vf-net-link-name.sh should always return a valid interface name.
Fixes: d7adfdf549f2 ("udev scripts: Support network interfaces rename on DPU only")
=> udev scripts: Prevent 82-net-setup-link.rules from setting invalid NAME

tsbin/mlnx-hugepages
Remove custom usage strings which sometimes led to incorrect results.
Use the set_defaults(func=...) pattern to set the action for a subcommand.
=> mlnx-hugepages: simplify args parsing

tsbin/mlnx_bf_configure
The referenced commit enabled OVS-DOCA configuration from the mlnx_bf_configure script, which requires an OVS restart. Currently if CREATE_OVS_BRIDGES flag is not set to "yes" the script exits without restarting This fix ensures that OVS is restarted even when
CREATE_OVS_BRIDGES is not set to "yes", by checking if a restart is necessary before exiting.
Issue: 4357112
Fixes: b20462ab1b14 ("mlnx_bf_configure: Enable OVS-DOCA as the default switch for BlueField")
=> mlnx_bf_configure: Add missing OVS restart.

python/mlnx_tune
commit 11e0c59 removed the OS's supported list, made the --list_os deprecated.
This commit remove the flag from the options list.
=> mlnx_tune: remove list_os option

tsbin/mlnx_bf_configure
Currently, hugepages are cleaned up for OVS-DOCA only when OVS_DOCA is set to "no". To handle invalid values, we should revert to the default "no" and cleanup hugepages.
=> mlnx_bf_configure: Cleanup hugepages for invalid OVS_DOCA values.

tsbin/mlnx-sf
Due to alignments of mlxdevm with upstream devlink, the output of $ mlxdevm port show now contains PFs as well as SFs. In order to avoid a crash, validate that "sfnum" attribute is present in the dictionary before printing SF's related data.
Issue: 4499738
=> tsbin/mlnx-sf: Fix mlnx-sf -a show command: sfnum

tsbin/mlnx_bf_configure
OVS creates and manages internal bridges and ports which can interfere with changing the eswitch mode. Therefore, we need to stop the OVS service (openvswitch-switch) before changing the eswitch mode to ensure a clean transition, and then start it again after changing the eswitch mode if it was active prior to the mode change.
Issue: 4409382
=> tsbin/mlnx_bf_configure: Stop OVS service before changing eswitch mode

debian/rules, mlnx-tools.spec, python/Python/dcbnetlink.py, python/ib2ib_setup, python/mlnx_dump_parser, python/mlnx_perf, python/mlnx_qos, python/mlnx_tune, python/mlx_fs_dump, python/tc_wrap.py
Package made python scripts python2 by default and converted them in "some cases" to python3. Just default to python3.
=> Make package python3-only

tsbin/mlnx-sf
Add a check for the roce field in the function dictionary to handle cases where the upstream devlink command does not provide this field in its JSON output, unlike the mlxdevm command it replaced.
Ensure the roce field defaults to "NA" when not present, matching the existing behavior for trust and eswitch fields.
Fix KeyError exception when running 'mlnx-sf -a show' with upstream devlink interface.
Fixes: 456712afd67e ("tsbin/mlnx-sf: Support upstream interface for SF")
=> tsbin/mlnx-sf: Add missing roce field check
